### ISSUE TITLE
heatsink too high

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Zotino#16]
The heat sink collides with neighbouring panel.

**Comment by gkasprow** [comment]
I want to replace it with ATS-56001-C3-R0. It has slightly lower thermal resistance but does not have mechanical assembly kit. 9mm vs previous 12.5mm should solve the issue.

**Comment by hartytp** [comment]
> but does not have mechanical assembly kit

how will you attach it to the PCB?

**Comment by gkasprow** [comment]
we will glue it, but with dual-compound thermal adhesive. Existing heat sinks were glued using dual sided bonding tape with copper core but it melted at higher temperature.

**Comment by hartytp** [comment]
Cool. If you think that's the right solution then it's fine by me
