### ISSUE TITLE
Zotino v1.1 testing:

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Zotino#21]
Things that I think are worth testing on Zotino v1.1:
- [x] Step response/rise time: switch from -10V to +10V and look at output on scope
- [ ] Noise spectrum with & without constant DAC updates. Look at +-FS and 0V
- [ ] Cross-talk (both before and after a 2m SCSI cable)
- [ ] Noise with TEC running
- [ ] Stability with + without TEC connected
- [ ] Small + large signal BW
- [ ] DC accuracy as a function of duty cycle (self-heating).

**Comment by gkasprow** [comment]
I connected a scope to CH2 and toggle CH1 output between 0x0000 and 0xFFFF and don't see any changes with a scope. At least they are lower than 5mV.

**Comment by hartytp** [comment]
Green trace is measured at the OpAmp side of R5 on DAC channel 0. Using a 20MHz BW here.

![image](https://user-images.githubusercontent.com/21218399/37904266-23dca40c-30f3-11e8-9649-fdfd2050076d.png)

Same but with some averaging

![image](https://user-images.githubusercontent.com/21218399/37904311-4d77391c-30f3-11e8-937e-687b9cf91187.png)

**Comment by hartytp** [comment]
If I do it, I'll probably use a battery powered OpAmp pre amp with gain of 100 and noise floor around 1nVrtHz. Put the whole thing in a metal box. Then take the data on a good scope. For the last factor of a few in noise we can take a cross-c9rrelation measurement using 2 pre amps and 2 scope channels.

But...I won't have time to do that any time soon.

I'll look at the stability and bw + cross-talk which I can do relatively quickly and leave the noise for another time/person.

**Comment by hartytp** [comment]
Anyway the 3561 only goes to 100kHz. The noise should be quite high there as it's above the filter cut-off. The interesting part imo is around 1MHz where the filter should be doing it's job.

**Comment by jordens** [comment]
The best high impedance voltage noise sensor around 1 MHz is ..... an ion. ;)
ACK everything. You can also do the correlation trick with some random other ADC pair at MHz.

**Comment by hartytp** [comment]
Noise model for Zotino

![screenshot from 2018-04-13 10-23-01](https://user-images.githubusercontent.com/21218399/38727364-b6539b64-3f04-11e8-89a7-fcc53fdcb194.png)

**Comment by pathfinder49** [comment]
> 
> 
>     * Those spurs are potentially worrying if they're not just pickup in your wiring?
> 
>     * It would be good to know: (a) do they correspond to any noise frequency generated by Zotino (e.g. the SMPS frequency) (b) are they affected by adding the screening cans to Zotino (c) are they affected by the proximity of Zotino to Kasli/any other local EMI source.
> 
>     * The high-frequency noise peak is also potentially worrying if it's real. Could be something like the PSRR of the OpAmps dropping off a cliff as they run out of gain BW. Maybe another measurement artifact?

For the benefit of others rummaging for Zotino noise performance like me. The spurs look very similar to some I observed when testing Fastino. I would wager many of them have the same source (an AC ground loop involving the Kasli SMPS). I have  written a detailed breakdown of how to reduce/eliminate these spurs in Fastino [here](https://github.com/sinara-hw/Fastino/issues/56). I imagine some of the techniques found to work with Fastino would also work for Zotino.
