### ISSUE TITLE
Temperature IDC should be 10-pin

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Zotino#23]
The I2C and power is not very useful. Design it to easily route to Thermostat via ribbon cable.

**Comment by sbourdeauducq** [comment]
The 10-pin connectors do not have I2C, though I am not sure why it was there in the first place. @gkasprow any comment?

**Comment by sbourdeauducq** [comment]
Seems we can just assemble a 10-pin IDC receptacle on Thermostat without changing the PCB design, the pinout is compatible.

**Comment by sbourdeauducq** [comment]
@hartytp I assume you meant 10-pin

**Comment by gkasprow** [comment]
we don't need I2c. I used a shorter connector, now it is compatible with Thermostat 10 pin one.
Pin 10 will be not used if you use IDC to DSUB9 cable

**Comment by gkasprow** [comment]
fixed in 1.4
