### ISSUE TITLE
Missing: IDC Connector Specs/Pitch

### ISSUE THREAD

**Issue by drewrisinger** [sinara-hw/Zotino#24]
The IDC connector pitch & number of positions is not specified in either this project's Wiki/README's, nor [BNC-IDC](https://github.com/sinara-hw/BNC_IDC).

Visually it looks like it's a 2x13 @ 0.1" pitch polarized IDC connector, but I would prefer to have some confirmation before buying appropriate connectors.

**Request**: update the Wiki of both Zotino & BNC_IDC with appropriate connector information.

**Comment by sbourdeauducq** [comment]
Those are very common connectors in electronics. If you want an easy way to obtain a Sinara system, you can purchase a pre-assembled crate including bitstreams, device database, etc.
Otherwise, writing this kind of basic documentation is a good first contribution.

**Comment by drewrisinger** [comment]
@sbourdeauducq they are a common connector TYPE, but it's also simultaneously vague. Like specifying "FPGA" or "IC". What package do those refer to? `DIP != QFN != SOIC != TO`. https://en.wikipedia.org/wiki/Insulation-displacement_connector.

Based on @sbourdeauducq's very helpful response, and hunting down the BOM hidden under [releases](https://github.com/sinara-hw/Zotino/releases), I see that they are .1" x .1" 2x13 polarized IDC connectors (Socket = 3M_N2526-6002RB).

Wiki editing is limited to members of the `sinara-hw` Github group, so it's not a contribution that I can actually make.

**Comment by gkasprow** [comment]
@drewrisinger if you want, I can give you access rights.

**Comment by drewrisinger** [comment]
@gkasprow Sure, I can edit a few things. It looks like the UMD section of https://github.com/sinara-hw/meta/wiki/Team also needs to be updated because postdocs and staff have moved on (https://github.com/sinara-hw/Fastino/issues/2#issuecomment-526807081)

**Comment by hartytp** [comment]
>  It looks like the UMD section of https://github.com/sinara-hw/meta/wiki/Team also needs to be updated because postdocs and staff have moved on (sinara-hw/Fastino#2 (comment))

I'd be more inclined to just scrap that section. Sinara usage has grown so fast that it's now very non-representative of the actual user base. It's also the kind of thing that tends to go out of date faster than it's updated so unlikely to be much help.

**Comment by drewrisinger** [comment]
@hartytp @jbqubit I have no preference on the wiki/Team section, it's interesting and useful for people on-boarding to get an idea of the team members, but it does fall out of date.
