### ISSUE TITLE
v1.2 incomplete IDC connector soldering

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Zotino#3]
![image](https://user-images.githubusercontent.com/1338946/40369759-07f34b7e-5ddf-11e8-88f0-68b73158ce1d.png)

**Comment by hartytp** [comment]
can we close this? What needs to be done?

**Comment by jordens** [comment]
The fabrication process should be checked and debugged so that these things don't happen.

**Comment by hartytp** [comment]
Okay. I think it's probably best to move this over to the `meta` project, since it is likely to effect all EEM designs.
