### ISSUE TITLE
HD68 Cables

### ISSUE THREAD

**Issue by andrewvh4** [sinara-hw/Zotino#34]
I'm having a hard time finding suppliers for the HD68 cables needed. Most suppliers list them as `obsolete` or `out of stock`. 

Does anyone know of a good supplier for these cables?

Also, if they are obsolete, is there any interest in changing the connector on the Zotino and related boards?

**Comment by gkasprow** [comment]
I usually source them from eBay or [Ali](https://www.aliexpress.com/item/32807697575.html) or [Amazon](https://www.amazon.com/Ribbon-Cable-Adapter-Connector-16-40ft/dp/B0B9LF4QPC/ref=sr_1_17?crid=1MUKNTM08KK38&keywords=scsi+68+cable&qid=1669151251&sprefix=scsi+68+cabl%2Caps%2C158&sr=8-17)
You can also use [crimped plugs](https://my.rs-online.com/web/p/scsi-connectors/7390732) with original Zotino connectors
Yet another idea is to use SCSI to VHDCI adapter and VHDCI cables.

Zotino/Fastino can be fitted with the original HD68 or [3M MDR connectors ](https://www.3m.com/3M/en_US/p/d/b00037030/). They are pin-compatible but not plug-compatible.
MDR68 cables are easier to source. I.e. [here](https://www.tti.com/content/dam/ttiinc/manufacturers/3m/PDF/MDRSelectionGuide.pdf) 
you can also make them using [IDC plugs](https://docs.rs-online.com/4164/0900766b8002f478.pdf) and ribbon cables
