### ISSUE TITLE
L1 and J2 collision

### ISSUE THREAD

**Issue by pkozakiewicz** [sinara-hw/Zotino#35]
Please see attached pictures, L1 should be moved away from IDC connector.

![WhatsApp Image 2023-01-24 at 14 38 14](https://user-images.githubusercontent.com/59871387/214309416-469dde3d-5f67-4af8-a596-2830cc8fb520.jpeg)
![WhatsApp Image 2023-01-24 at 14 36 54](https://user-images.githubusercontent.com/59871387/214309419-93c8bc11-2059-4656-85db-ff715e9b66e0.jpeg)

**Comment by filipswit** [comment]
fixed in v1.4.2
