### ISSUE TITLE
Switch DAC package

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Zotino#5]
Looks like the AD5372BCPZ (LFCSP package) is being discontinued http://www.analog.com/media/en/PCN/ADI_PDN_16_0050_Rev_B_Form.pdf p47.

Replacement is the AD5372BSTZ (LQFP). Let's switch to that for the next revision as the availability seems to be better (although, the thermal impedance is marginally higher).

**Comment by dhslichter** [comment]
Sounds good to me.

**Comment by gkasprow** [comment]
well, they say that "PDN is no longer applicable for this part.It has been removed on this version of the PDN"
It's available now.

**Comment by hartytp** [comment]
@gkasprow okay, if it's no longer depreciated then we can keep the current package. However, I still had the impression that the package we are using is harder to get hold of (fewer people seem to stock it), so we might want to change anyway. I'll leave that to you.

**Comment by gkasprow** [comment]
I managed to place both footprints so any package can be installed.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/44118756-6a7c91cc-a017-11e8-9c98-5321f8cc55bb.png)

**Comment by hartytp** [comment]
:) that solves that problem
