### ISSUE TITLE
Zotino rev1.1 issue 

### ISSUE THREAD

**Issue by prasath-d** [sinara-hw/Zotino#7]
Hello,
I am using zotino rev1.1 with kasli as a controller.
I tried to set the voltages in the DAC channel by using the code given in the demo program.
```
import numpy as np
from artiq.experiment import *

class zotino_demo(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("zotino0")

    @kernel
    def run(self):
        self.core.reset()
        self.zotino0.init()
        delay(100*ms)
        while True:
            self.zotino0.set_leds(0xff)
            delay(100*ms)
            self.zotino0.set_dac(
                [-9. + i*.5 for i in range(32)],
                list(range(32))
            )

```
The output I got from one of the channel was
![img_20180702_174214](https://user-images.githubusercontent.com/40395150/42217411-624c1392-7ec5-11e8-89cd-63b3c84f66f4.jpg)
There is a deadtime of 2s between every 600ms.
Then tried to understand the problem by modifying the code.
```
import numpy as np
from artiq.experiment import *

class zotino_demo2(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("zotino0")

    @kernel
    def run(self):
        self.core.reset()
        delay(100*ms)        
        self.zotino0.init()
        while True:
            self.zotino0.set_leds(0xff)
            delay(10*ms)
            self.zotino0.set_dac(
                [-9. + i*.5 for i in range(32)],
                list(range(32))
            )
            delay(10*ms)
            self.zotino0.set_dac(
                [9. - i*.5 for i in range(32)],
                list(range(32))
            )
            delay(10*ms)

```
This switches the output voltage every 10ms from positive to negative and, I saw the same
![img_20180703_131934](https://user-images.githubusercontent.com/40395150/42217504-c163e7f6-7ec5-11e8-965f-036c8afac253.jpg)
The output works for 600ms and stops working for 2s.

I recorded the output, when no program is running.
![img_20180703_132248](https://user-images.githubusercontent.com/40395150/42217537-e18aa4c0-7ec5-11e8-8387-9ef36f87cf05.jpg)
where, there is a noise output of around ~10mv which is also having 600ms width and 2s of deadtime.
could you please help me in understanding this issue. is it a hardware issue or I am missing something?
Thank you

**Comment by hartytp** [comment]
https://github.com/sinara-hw/Zotino/issues/2 :(

**Comment by jbqubit** [comment]
cf https://github.com/sinara-hw/Zotino/issues/2#issuecomment-403926712
