### ISSUE TITLE
jack screws

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Zotino#8]
We tend to use screw in HD68 cables rather than the clip in ones. Unless anyone objects, can we add the jack screws for the HD68 connector to the BOM and have them populated by default?

**Comment by jordens** [comment]
Yes. And open up the panel to give access to the threads (Zotino, HD68IDC, Grabber). I think I filed an issue about that but can't find it right now.

**Comment by gkasprow** [comment]
added 2x 786585-2

**Comment by hartytp** [comment]
@gkasprow thanks! Did you change the panel cut out as well?

**Comment by gkasprow** [comment]
yes
